meta_product_name: "Humus"
meta_title: "Humus Eco-Projets in France"
meta_description: "Investissez dans les éco-projets Humus pour que la campagne reste verte."
meta_image: "banner_og.png" # should exist in `app/assets/images/`

# twitter_account: "@product_twitter_account"   # required for Twitter Cards
